### ISSUE TITLE
Minecraft server properties difficulty not working

### ISSUE THREAD

**Issue by nitvit610** [GameServerManagers/Game-Server-Configs#129]
In /gameserver/serverfiles/server.properties where difficulty=easy/medium/hard this is not working.
On my server I have set this value to hard, however running the command difficulty from the server console just shows Easy.

I have tried varying values for difficulty (Hard, hard, 3), however the server is just running as Easy.

Setting the difficulty from the console works e.g. difficulty hard 
Setting it this way seems to persist even when changing it to other values in server.properties like setting it to easy, the server stays as hard through reboots.

**Comment by Claiyc** [comment]
Not an issue with lgsm, neither with this repository. Please ask your question on our discord: https://linuxgsm.com/discord or open a discussion here: https://github.com/GameServerManagers/LinuxGSM/discussions/new
