### ISSUE TITLE
Addition of PaperMC Config Files

### ISSUE THREAD

**Issue by RaspberryPicardBox** [GameServerManagers/Game-Server-Configs#136]
When running a new instillation of a PaperMC server, the following error is presented. This is visible in install, update, start, etc.

default configs from https://github.com/GameServerManagers/Game-Server-Configs
fetching GitHub server.properties...curl: (22) The requested URL returned error: 404
ERROR
fetching Bitbucket server.properties...curl: (22) The requested URL returned error: 404
FAIL

**Comment by h3o66** [comment]
thanks for the report, this should be fixed with the commit:
https://github.com/GameServerManagers/Game-Server-Configs/commit/bb25ee25cb9cdfc4987ff817153b3e5e2793e143
I tested it and it works now
