### ISSUE TITLE
CS2 start map should be specified

### ISSUE THREAD

**Issue by Nuc1eoN** [GameServerManagers/Game-Server-Configs#140]
I have set up a new CS2 server but it fails to run.

It turned out after a lot of trial and error, that the start map is commented out in `cs2server.cfg`.

It seem this has been done deliberately in 00cf041e2b93e101c2c2ae73ddf105ed1863e042

Please revert this change or add a start map to the startup parameters another way. E.g. as suggested in https://github.com/GameServerManagers/LinuxGSM/issues/4447#issuecomment-1906134225.

Because otherwise the CS2 server will fail to run.

**Comment by dgibbs64** [comment]
I have moved all the convars (e.g +map in start parameters) from the start parameters to the main config. This is to unify convars into 1 place rather than them being split between start parameters and the config. Start parameters (e.g -port) remain in the same place
