### ISSUE TITLE
Security issue with default admin passwords

### ISSUE THREAD

**Issue by sannysc** [GameServerManagers/Game-Server-Configs#38]
Having default passwords for admin systems is incredibly dangerous. What it means is that anyone can join random servers and have a pretty good chance of gaining admin access. Inexperienced server hosts may not even know that they should change them. Instead of having admin passwords in the config, admin access should be disabled by default, and hosts must set up the admin password themselves. This ensures that malicious users can't go around attempting to use `ADMINPASSWORD` everywhere.

**Comment by dgibbs64** [comment]
ADMINPASSWORD is used as a variable in LinuxGSM to create a random password on install. Every game server works differently as well so there may not be an option to disable admin depending on the game server. If LinuxGSM is used there is no issue at all. If an admin is using this repo as a reference it's up to them to edit the passwords themselves. There is only so much I can mitagate against inexperiance. Securing a game server login is server admin 101. I could also argue that not including any admin info an inexperianced admin might not even be aware of setting an admin password.

**Comment by sannysc** [comment]
If it gets replaced in linuxgsm, this isn't a problem 👍
