### ISSUE TITLE
HowTo Disable Bots in csgoserver

### ISSUE THREAD

**Issue by DerP9** [GameServerManagers/Game-Server-Configs#96]
Hello Guys,

can you tell me how can i disable bots in csgoserver?

I have tried already bot_quota.

Thank you very much.

Kind regards

**Comment by Clanwarz** [comment]
Try adding -nobots to your command line until you find how to do it via configure files.

**Comment by borzaka** [comment]
`-nobots` starting command has a [known issue](https://forums.alliedmods.net/showthread.php?t=261158): you can see enemies thru smoke on the radar. So it's not recommended.

`bot_quota 0` is also buggy, and not working reliably.

Your best option is to use a 3rd party SourceMod plugin:
https://forums.alliedmods.net/showthread.php?t=237004

I'am using this, and it's working fine.
